export const ERROR_CODES = {
  // Authentication Errors
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',

  // Validation Errors
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
  VALIDATION_INVALID_LENGTH: 'VALIDATION_INVALID_LENGTH',
  VALIDATION_INVALID_RANGE: 'VALIDATION_INVALID_RANGE',
  VALIDATION_INVALID_TYPE: 'VALIDATION_INVALID_TYPE',
  VALIDATION_INVALID_ENUM: 'VALIDATION_INVALID_ENUM',
  VALIDATION_PATTERN_MISMATCH: 'VALIDATION_PATTERN_MISMATCH',

  // Booking Errors
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_INVALID_DATES: 'BOOKING_INVALID_DATES',
  BOOKING_UNAVAILABLE: 'BOOKING_UNAVAILABLE',
  BOOKING_CAPACITY_EXCEEDED: 'BOOKING_CAPACITY_EXCEEDED',
  BOOKING_INVALID_GUEST_COUNT: 'BOOKING_INVALID_GUEST_COUNT',
  BOOKING_ALREADY_EXISTS: 'BOOKING_ALREADY_EXISTS',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_MODIFICATION_NOT_ALLOWED: 'BOOKING_MODIFICATION_NOT_ALLOWED',
  BOOKING_PAYMENT_REQUIRED: 'BOOKING_PAYMENT_REQUIRED',

  // Session Errors
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_INVALID_STATE: 'SESSION_INVALID_STATE',
  SESSION_INVALID_TRANSITION: 'SESSION_INVALID_TRANSITION',
  SESSION_LIMIT_EXCEEDED: 'SESSION_LIMIT_EXCEEDED',
  SESSION_ABANDONED: 'SESSION_ABANDONED',

  // Payment Errors
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_DECLINED: 'PAYMENT_DECLINED',
  PAYMENT_INSUFFICIENT_FUNDS: 'PAYMENT_INSUFFICIENT_FUNDS',
  PAYMENT_INVALID_CARD: 'PAYMENT_INVALID_CARD',
  PAYMENT_EXPIRED_CARD: 'PAYMENT_EXPIRED_CARD',
  PAYMENT_PROCESSING_ERROR: 'PAYMENT_PROCESSING_ERROR',
  PAYMENT_GATEWAY_ERROR: 'PAYMENT_GATEWAY_ERROR',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',

  // Rate Limiting Errors
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  THROTTLE_LIMIT_EXCEEDED: 'THROTTLE_LIMIT_EXCEEDED',

  // Resource Errors
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RESOURCE_LOCKED: 'RESOURCE_LOCKED',
  RESOURCE_UNAVAILABLE: 'RESOURCE_UNAVAILABLE',

  // Database Errors
  DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
  DATABASE_QUERY_ERROR: 'DATABASE_QUERY_ERROR',
  DATABASE_CONSTRAINT_VIOLATION: 'DATABASE_CONSTRAINT_VIOLATION',
  DATABASE_DEADLOCK: 'DATABASE_DEADLOCK',
  DATABASE_TIMEOUT: 'DATABASE_TIMEOUT',

  // External Service Errors
  EXTERNAL_SERVICE_UNAVAILABLE: 'EXTERNAL_SERVICE_UNAVAILABLE',
  EXTERNAL_SERVICE_TIMEOUT: 'EXTERNAL_SERVICE_TIMEOUT',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  INTEGRATION_ERROR: 'INTEGRATION_ERROR',
  THIRD_PARTY_API_ERROR: 'THIRD_PARTY_API_ERROR',

  // Configuration Errors
  CONFIG_MISSING: 'CONFIG_MISSING',
  CONFIG_INVALID: 'CONFIG_INVALID',
  ENVIRONMENT_ERROR: 'ENVIRONMENT_ERROR',

  // General System Errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  MAINTENANCE_MODE: 'MAINTENANCE_MODE',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  VERSION_MISMATCH: 'VERSION_MISMATCH',

  // Network Errors
  NETWORK_ERROR: 'NETWORK_ERROR',
  CONNECTION_TIMEOUT: 'CONNECTION_TIMEOUT',
  CONNECTION_REFUSED: 'CONNECTION_REFUSED',
  DNS_RESOLUTION_ERROR: 'DNS_RESOLUTION_ERROR',

  // File/Upload Errors
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_SUPPORTED: 'FILE_TYPE_NOT_SUPPORTED',
  UPLOAD_FAILED: 'UPLOAD_FAILED',

  // Analytics Errors
  ANALYTICS_EVENT_INVALID: 'ANALYTICS_EVENT_INVALID',
  ANALYTICS_TRACKING_ERROR: 'ANALYTICS_TRACKING_ERROR',
  METRICS_COLLECTION_ERROR: 'METRICS_COLLECTION_ERROR'
} as const;

export const ERROR_MESSAGES = {
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'Authentication token has expired',
  [ERROR_CODES.AUTH_TOKEN_INVALID]: 'Invalid authentication token',
  [ERROR_CODES.AUTH_TOKEN_MISSING]: 'Authentication token is required',
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 'Invalid username or password',
  [ERROR_CODES.AUTH_ACCOUNT_LOCKED]: 'Account is temporarily locked',
  [ERROR_CODES.AUTH_ACCOUNT_DISABLED]: 'Account has been disabled',
  [ERROR_CODES.AUTH_INSUFFICIENT_PERMISSIONS]: 'Insufficient permissions to access this resource',
  [ERROR_CODES.AUTH_SESSION_EXPIRED]: 'Session has expired',

  [ERROR_CODES.VALIDATION_REQUIRED_FIELD]: 'This field is required',
  [ERROR_CODES.VALIDATION_INVALID_FORMAT]: 'Invalid format',
  [ERROR_CODES.VALIDATION_INVALID_LENGTH]: 'Invalid length',
  [ERROR_CODES.VALIDATION_INVALID_RANGE]: 'Value is outside the allowed range',
  [ERROR_CODES.VALIDATION_INVALID_TYPE]: 'Invalid data type',
  [ERROR_CODES.VALIDATION_INVALID_ENUM]: 'Value is not one of the allowed options',
  [ERROR_CODES.VALIDATION_PATTERN_MISMATCH]: 'Value does not match the required pattern',

  [ERROR_CODES.BOOKING_NOT_FOUND]: 'Booking not found',
  [ERROR_CODES.BOOKING_INVALID_DATES]: 'Invalid booking dates',
  [ERROR_CODES.BOOKING_UNAVAILABLE]: 'No availability for the selected dates',
  [ERROR_CODES.BOOKING_CAPACITY_EXCEEDED]: 'Room capacity exceeded',
  [ERROR_CODES.BOOKING_INVALID_GUEST_COUNT]: 'Invalid number of guests',
  [ERROR_CODES.BOOKING_ALREADY_EXISTS]: 'Booking already exists for these dates',
  [ERROR_CODES.BOOKING_CANCELLED]: 'Booking has been cancelled',
  [ERROR_CODES.BOOKING_MODIFICATION_NOT_ALLOWED]: 'Booking cannot be modified',
  [ERROR_CODES.BOOKING_PAYMENT_REQUIRED]: 'Payment is required to complete the booking',

  [ERROR_CODES.SESSION_NOT_FOUND]: 'Session not found',
  [ERROR_CODES.SESSION_EXPIRED]: 'Session has expired',
  [ERROR_CODES.SESSION_INVALID_STATE]: 'Invalid session state',
  [ERROR_CODES.SESSION_INVALID_TRANSITION]: 'Invalid session state transition',
  [ERROR_CODES.SESSION_LIMIT_EXCEEDED]: 'Maximum number of sessions exceeded',
  [ERROR_CODES.SESSION_ABANDONED]: 'Session has been abandoned',

  [ERROR_CODES.PAYMENT_FAILED]: 'Payment failed',
  [ERROR_CODES.PAYMENT_DECLINED]: 'Payment was declined',
  [ERROR_CODES.PAYMENT_INSUFFICIENT_FUNDS]: 'Insufficient funds',
  [ERROR_CODES.PAYMENT_INVALID_CARD]: 'Invalid card details',
  [ERROR_CODES.PAYMENT_EXPIRED_CARD]: 'Card has expired',
  [ERROR_CODES.PAYMENT_PROCESSING_ERROR]: 'Payment processing error',
  [ERROR_CODES.PAYMENT_GATEWAY_ERROR]: 'Payment gateway error',
  [ERROR_CODES.PAYMENT_AMOUNT_MISMATCH]: 'Payment amount does not match booking total',

  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Rate limit exceeded',
  [ERROR_CODES.QUOTA_EXCEEDED]: 'Usage quota exceeded',
  [ERROR_CODES.THROTTLE_LIMIT_EXCEEDED]: 'Request throttle limit exceeded',

  [ERROR_CODES.RESOURCE_NOT_FOUND]: 'Resource not found',
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: 'Resource already exists',
  [ERROR_CODES.RESOURCE_CONFLICT]: 'Resource conflict',
  [ERROR_CODES.RESOURCE_LOCKED]: 'Resource is locked',
  [ERROR_CODES.RESOURCE_UNAVAILABLE]: 'Resource is temporarily unavailable',

  [ERROR_CODES.DATABASE_CONNECTION_ERROR]: 'Database connection error',
  [ERROR_CODES.DATABASE_QUERY_ERROR]: 'Database query error',
  [ERROR_CODES.DATABASE_CONSTRAINT_VIOLATION]: 'Database constraint violation',
  [ERROR_CODES.DATABASE_DEADLOCK]: 'Database deadlock detected',
  [ERROR_CODES.DATABASE_TIMEOUT]: 'Database operation timeout',

  [ERROR_CODES.EXTERNAL_SERVICE_UNAVAILABLE]: 'External service is unavailable',
  [ERROR_CODES.EXTERNAL_SERVICE_TIMEOUT]: 'External service timeout',
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 'External service error',
  [ERROR_CODES.INTEGRATION_ERROR]: 'Integration error',
  [ERROR_CODES.THIRD_PARTY_API_ERROR]: 'Third-party API error',

  [ERROR_CODES.CONFIG_MISSING]: 'Required configuration is missing',
  [ERROR_CODES.CONFIG_INVALID]: 'Configuration is invalid',
  [ERROR_CODES.ENVIRONMENT_ERROR]: 'Environment configuration error',

  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 'Internal server error',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 'Service is temporarily unavailable',
  [ERROR_CODES.MAINTENANCE_MODE]: 'Service is in maintenance mode',
  [ERROR_CODES.FEATURE_DISABLED]: 'This feature is currently disabled',
  [ERROR_CODES.VERSION_MISMATCH]: 'API version mismatch',

  [ERROR_CODES.NETWORK_ERROR]: 'Network error',
  [ERROR_CODES.CONNECTION_TIMEOUT]: 'Connection timeout',
  [ERROR_CODES.CONNECTION_REFUSED]: 'Connection refused',
  [ERROR_CODES.DNS_RESOLUTION_ERROR]: 'DNS resolution error',

  [ERROR_CODES.FILE_NOT_FOUND]: 'File not found',
  [ERROR_CODES.FILE_TOO_LARGE]: 'File size exceeds the maximum limit',
  [ERROR_CODES.FILE_TYPE_NOT_SUPPORTED]: 'File type is not supported',
  [ERROR_CODES.UPLOAD_FAILED]: 'File upload failed',

  [ERROR_CODES.ANALYTICS_EVENT_INVALID]: 'Invalid analytics event',
  [ERROR_CODES.ANALYTICS_TRACKING_ERROR]: 'Analytics tracking error',
  [ERROR_CODES.METRICS_COLLECTION_ERROR]: 'Metrics collection error'
} as const;

export const ERROR_CATEGORIES = {
  AUTHENTICATION: 'authentication',
  VALIDATION: 'validation',
  BOOKING: 'booking',
  SESSION: 'session',
  PAYMENT: 'payment',
  RATE_LIMITING: 'rate_limiting',
  RESOURCE: 'resource',
  DATABASE: 'database',
  EXTERNAL_SERVICE: 'external_service',
  CONFIGURATION: 'configuration',
  SYSTEM: 'system',
  NETWORK: 'network',
  FILE: 'file',
  ANALYTICS: 'analytics'
} as const;

export function getErrorCategory(errorCode: string): string | null {
  if (errorCode.startsWith('AUTH_')) return ERROR_CATEGORIES.AUTHENTICATION;
  if (errorCode.startsWith('VALIDATION_')) return ERROR_CATEGORIES.VALIDATION;
  if (errorCode.startsWith('BOOKING_')) return ERROR_CATEGORIES.BOOKING;
  if (errorCode.startsWith('SESSION_')) return ERROR_CATEGORIES.SESSION;
  if (errorCode.startsWith('PAYMENT_')) return ERROR_CATEGORIES.PAYMENT;
  if (errorCode.startsWith('RATE_LIMIT_') || errorCode.startsWith('QUOTA_') || errorCode.startsWith('THROTTLE_')) {
    return ERROR_CATEGORIES.RATE_LIMITING;
  }
  if (errorCode.startsWith('RESOURCE_')) return ERROR_CATEGORIES.RESOURCE;
  if (errorCode.startsWith('DATABASE_')) return ERROR_CATEGORIES.DATABASE;
  if (errorCode.startsWith('EXTERNAL_') || errorCode.startsWith('INTEGRATION_') || errorCode.startsWith('THIRD_PARTY_')) {
    return ERROR_CATEGORIES.EXTERNAL_SERVICE;
  }
  if (errorCode.startsWith('CONFIG_') || errorCode.startsWith('ENVIRONMENT_')) return ERROR_CATEGORIES.CONFIGURATION;
  if (errorCode.startsWith('NETWORK_') || errorCode.startsWith('CONNECTION_') || errorCode.startsWith('DNS_')) {
    return ERROR_CATEGORIES.NETWORK;
  }
  if (errorCode.startsWith('FILE_') || errorCode.startsWith('UPLOAD_')) return ERROR_CATEGORIES.FILE;
  if (errorCode.startsWith('ANALYTICS_') || errorCode.startsWith('METRICS_')) return ERROR_CATEGORIES.ANALYTICS;

  return ERROR_CATEGORIES.SYSTEM;
}

export function getErrorMessage(errorCode: string): string {
  return ERROR_MESSAGES[errorCode as keyof typeof ERROR_MESSAGES] || 'An unexpected error occurred';
}